#!/usr/bin/env bash

## Install Homebrew if not installed
if ! command -v brew &> /dev/null; then
    echo "Homebrew not found, installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

/opt/homebrew/bin/brew update
/opt/homebrew/bin/brew install curl git ansible

ansible-pull -U https://github.com/nathankoerschner/ansible.git --ask-become-pass --ask-vault-pass

