- name: Ensure Homebrew is installed
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:nathankoerschner/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master

