- name: Ensure Homebrew is installed
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew

- name: Cloning .dotfiles using gh CLI
  ansible.builtin.command:
    cmd: >
      gh repo clone git@github.com:nathankoerschner/dotfiles.git 
      "{{ lookup('env', 'HOME') }}/dotfiles"
  args:
    chdir: "{{ lookup('env', 'HOME') }}"

