- name: Installing stow
  homebrew:
    name: stow
    state: present

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:nathankoerschner/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main

- name: MacOS settings
  shell: cd $HOME/.dotfiles && ./macos

