- name: Ensure Homebrew is installed
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew
  tags:
    - install
    - dotfiles
    - stow

- name: Installing stow
  ansible.builtin.brew:
    name: stow
    state: present
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:nathankoerschner/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  ansible.builtin.shell: |
    cd {{ lookup('env', 'HOME') }}/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow

