- name: Download 1Password ZIP
  get_url:
    url: https://downloads.1password.com/mac/1Password.zip
    dest: /tmp/1Password.zip

- name: Unzip 1Password
  unarchive:
    src: /tmp/1Password.zip
    dest: /tmp/
    remote_src: yes

- name: Remove existing 1Password app if present
  file:
    path: /Applications/1Password.app
    state: absent
  become: yes

- name: Open 1Password Installer.app
  command: open /tmp/1Password\ Installer.app
  become: yes

- name: Clean up ZIP file
  file:
    path: /tmp/1Password.zip
    state: absent
