- name: Install packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - tmux
    - fzf
    - tldr
    - ripgrep
    - hammerspoon
  tags:
    - install
    - productivity
- name: Open Hammerspoon
  command: open /Applications/Hammerspoon.app
