- name: Install ZSH
  homebrew:
    name: zsh
    state: present
  become: false

- name: Add zsh to the list of valid shells
  lineinfile:
    path: /etc/shells
    line: "{{ lookup('pipe', 'which zsh') }}"
    state: present
  become: true

- name: Change default shell to zsh for this user
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ lookup('pipe', 'which zsh') }}"

- name: Install Oh My Zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh
  become: false

